<?php $posts = $this->getPosts(); ?>

  <section class="mini-slider section-strt">
            <div class="container">
               <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-6 col-12">
                     <div class="mini-main">
                        <h2>Our Customer Says</h2>
                     </div>
                  </div>
               </div>


<section class="slider">
	<div class="demo">
        <div class="item">            
            <div class="clearfix">
                <ul id="image-gallery" class="gallery list-unstyled cS-hidden">

                  <?php foreach ($posts as $post): ?>

                  <?php $category = $post->Cats;  

                   foreach ($category as $cate) {

                    $cate_title = $cate['title'];

                    if($cate_title == 'Testimonials'){ 

                    ?>
                    <li> 
                        <div class="mini-main-content">
                              <div class="mini-left">
                                <img class="client-img" src="<?php echo Mage::getBaseUrl('media') . $post->getThumb(); ?>" <?php echo ($post->getImageRetina() ? 'data-srcX2="'.Mage::getBaseUrl('media') . $post->getImageRetina().'"' : '' ); ?>>
                                 <!-- <img src="<?php echo Mage::getBaseUrl('media') ?>/custom/default.png"> -->
                                 <h2><?php echo $post->getTitle(); ?></h2>
                                 <?php $t = strtotime($post->getOrigData('created_time')); ?>
                                 <p>(
                                   <?php echo '<span class="day">'.date('d', $t).'</span> '.'<span class="month">'.date('M', $t).', </span><span class="year">'.date('Y', $t).'</span>'; ?>
                                   )
                                 </p>
                              </div>
                              <p class="testimonials-content">
                                <?php echo $post->getPostContent(); ?> 
                              </p>
                           </div>
                         </li>
                    <?php

                  }    // End if
                     }   // End second foreach 

                     ?>

                   <?php endforeach; ?>
                      
                    
                </ul>
            </div>
        </div>
       

    </div>	
 </section>
               <div class="view-btn">
                  <span><a href="<?php echo Mage::getBaseUrl(); ?>blog/cat/testimonials/">View All</a></span>
               </div>
            </div>
         </section>
      
  
   
