<?php $posts = $this->getPosts(); ?>
         <section class="gallery-sec section-strt">
            <div class="container">
               <div class="gallery-main">
                  <h2>Customer Gallery</h2>
                  <p class="gallery-btn">
                     <span><a href="#" class="imgs-btn">Images</a></span>
                     <span><a href="#" class=vid-btn>Videos</a></span>
                  </p>
               </div>
               <div class="row">
                  <div class="col-lg-3 col-md-6 col-sm-6">
                     <div class="g-top-img">
                        <img src="assets/images/g-img1.png">
                     </div>
                     <div class="g-bottom-img">
                        <img src="assets/images/g-img5.png">
                     </div>
                  </div>
                  <div class="col-lg-3 col-md-6 col-sm-6">
                     <div class="g-top-img">
                        <img src="assets/images/g-img2.png">
                     </div>
                     <div class="g-bottom-img">
                        <img src="assets/images/g-img6.png">
                     </div>
                  </div>
                  <div class="col-lg-3 col-md-6 col-sm-6">
                     <div class="g-top-img">
                        <img src="assets/images/g-img3.png">
                     </div>
                     <div class="g-bottom-img">
                        <img src="assets/images/g-img7.png">
                     </div>
                  </div>
                  <div class="col-lg-3 col-md-6 col-sm-6">
                     <div class="g-top-img">
                        <img src="assets/images/g-img4.png">
                     </div>
                     <div class="g-bottom-img">
                        <img src="assets/images/g-img8.png">
                     </div>
                  </div>
               </div>
              <div class="view-btn">
                  <span><a>View All</a></span>
               </div>
            </div>
              
         </section>
         
<section class="home-blog-posts">
<div id="messages_product_view">
    <?php Mage::app()->getLayout()->getMessagesBlock()->setMessages(Mage::getSingleton('customer/session')->getMessages(true)); ?>
    <?php echo Mage::app()->getLayout()->getMessagesBlock()->getGroupedHtml(); ?>
</div>
<!-- <div class="blog-title">
	<h1><?php echo Mage::getStoreConfig('blog/blog/title'); ?></h1>
</div> -->
<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>
<?php $i = 1; ?>
<div class="posts-main grid_18">
<?php foreach ($posts as $post): ?>

	<div class="post-inner one_third">

    <div class="postWrapper">
	    <?php if ($post->getImage()) : list($width, $height, $type, $attr) = getimagesize(Mage::getBaseUrl('media'). $post->getImage()); ?>
		<div class="blog-img-wrap">
			<a class="blog-img-link" href="<?php echo $post->getAddress(); ?>">
				<img <?php echo $attr; ?> class="blog-img" src="<?php echo Mage::getBaseUrl('media') . $post->getImage(); ?>" <?php echo ($post->getImageRetina() ? 'data-srcX2="'.Mage::getBaseUrl('media') . $post->getImageRetina().'"' : '' ); ?>>
			</a>
		</div>
	    <?php endif; ?>
	    <div class="post-content">
	    	<div class="postContentWrapper">	
			<div class="postTitle">				
				<h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle(); ?></a></h2>
				 <h3 class="blog-date">
			<div class="inner">
			<?php
			$t = strtotime($post->getOrigData('created_time'));?>			
			<span class="day"><?php echo $day = date('d', $t) ?></span><?php echo " ".$this->__($month=date('M', $t)); echo ','.date('Y',$t);?> 			
			</div>
			
		</h3>
				
			</div>
			<div class="postContent std"><?php echo $post->getShortContent(); ?>
				
				<a href="<?php echo $post->getAddress(); ?>" class="read-more">Read more </a>
			</div>
			
		 </div>	
		 </div>	
    </div>
</div>
<?php if($i % 3 == 0) {echo '</div><div class="posts-main grid_18">';}
$i++;
?>
<?php endforeach; ?>
</div>
</section>
<?php //echo $this->getChildHtml('aw_blog_comments_toolbar'); ?>