<div class="appreal-main">
                 <a href="#" class="apperal">Apperal Configurator</a>
                 <img class="config-img" src="assets/images/config-app.png">
                 
                 <ul class="social-icons">
                 
                     <li  class="facebook"><a><i class="fab fa-facebook-f"></i></a></li>
                     <li class="twitter"><a ><i class="fab fa-twitter"></i></a></li>
                     <li class="google"><a ><i class="fab fa-google-plus-g"></i></a></li>
                     <li class="whatsapp"><a><i class="fab fa-whatsapp"></i></a></li>
                     <li class="plus"><a><i class="fas fa-plus"></i></a></li>
                 
                 </ul>
                  <h2 class="appreal-messenger"><img src="assets/images/messenger.png"></h2>
             </div>