<?php 
$_helper = Mage::helper('catalog/category');
$_categories = $_helper->getStoreCategories();

?>

               <div class="sale-feature-products">
                <?php

                if (count($_categories) > 0){

    foreach($_categories as $_category){
        // print_r($_category);exit;
        $_category = Mage::getModel('catalog/category')->load($_category->getId());
        $home_category = $_category->getName();

        if($home_category == 'Sale-Feature'){

        $_subcategories = $_category->getChildrenCategories(); ?>

        <div class="main">

        <?php
        if (count($_subcategories) > 0){
            // echo $_category->getName();
            // echo $_category->getId();      
            foreach($_subcategories as $_subcategory){
                ?>
                 <a href="#<?php echo $_subcategory->getId();?>" class="f-btn"><?php echo $_subcategory->getName(); ?></a>
                 
                 
            <?php }
            ?>
            </div>
  

        <?php 
    }


foreach($_subcategories as $_subcategory){
$categoryid = $_subcategory->getId(); // Category Id

$category = new Mage_Catalog_Model_Category();
$category->load($categoryid);
$collection = $category->getProductCollection();
$collection->addAttributeToSelect('*'); 

?>




<?php foreach ($collection as $_product) { ?>

<div class="" >
                     <div class="main-box text-center">
                        <h3><?php echo $_product->getName(); ?></h3>
                        <div class="box-img">
                             <a href="<?php echo $_product->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(200); ?>" width="200" height="200" class="img-fluid" alt="" /></a> 


                        
                        </div>
                        <div class="desc">
                           <p>
                            <?php echo Mage::app()->getLayout()->createBlock('catalog/product')->getPriceHtml($_product); ?>
                              <?php //echo $this->getPriceHtml($_product, true) ?>
                           </p>
                        </div>
                        <div class="desc-btn">
                           <ul>
                              <li>
<a title="<?php echo $this->__('View Details') ?>" class="detail-btn" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Details') ?></a>


                                <!-- <a href="#" class="detail-btn">View Details</a></li> -->
                              <li>
<button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="add-to-cart-btn" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                <!-- <a href="#" class="add-to-cart-btn">Add to Cart</a></li> -->
                           </ul>
                        </div>
                     </div>
                  </div>
<?php }
?>


<?php }

?>

<?php
    }

    }
    
    }

?>


                  
                    
                   
                
                
               </div>
            