 <section class="lg-banner-main section-strt">
            <div class="container">
               <div class="row">
                  <div>



                     
                     <div class="banner-box">
                        <img src="<?php echo Mage::getBaseUrl('media');?>/custom/banner1.png" class="img-fluid">
                        <div class="banner-content">
                           <h3>Design your own Apperal</h3>
                           <p>With Gomax Racing Gear</p>
                           <p><a>Go to Apperal</a></p>


                           <?php
                         


                           ?>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </section>