<?php if ($this->canShip()) : ?>
<?php $blockNumber = $this->getBlockNumber();?>
<?php $blockNumberClass = (!is_null($blockNumber))?"olegnax-osc-icon-{$blockNumber}":"";?>
<div id="olegnax-osc-shipping-method" class="olegnax-osc-block-wrap">
    <h3 class="olegnax-osc-icon <?php echo $blockNumberClass;?>"><?php echo $this->__('Shipping Method'); ?></h3>
    <div class="olegnax-osc-block-content olegnax-osc-add-loader-into-this-block">
        <?php $_shippingRateGroups = $this->getShippingRates(); ?>
        <?php if (!$_shippingRateGroups) : ?>
            <p><?php echo $this->__('Please specify the shipping address to see available options.') ?></p>
        <?php else : ?>
            <dl class="sp-methods">
            <?php $_sole = count($_shippingRateGroups) == 1; foreach ($_shippingRateGroups as $code => $_rates): ?>
                <dt><?php echo $this->escapeHtml($this->getCarrierName($code)) ?></dt>
                <dd>
                    <ul>
                    <?php $_sole = $_sole && count($_rates) == 1; foreach ($_rates as $_rate): ?>
                        <li>
                            <?php if ($_rate->getErrorMessage()): ?>
                                <ul class="messages"><li class="error-msg"><ul><li><?php echo $this->escapeHtml($_rate->getErrorMessage()) ?></li></ul></li></ul>
                            <?php else: ?>
                                <?php if ($_sole) : ?>
                                    <span class="no-display"><input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>" checked="checked" /></span>
                                <?php else: ?>
                                    <input name="shipping_method" type="radio" value="<?php echo $_rate->getCode() ?>" id="s_method_<?php echo $_rate->getCode() ?>"<?php if($_rate->getCode()===$this->getAddressShippingMethod()) echo ' checked="checked"' ?> class="radio"/>
                                <?php endif; ?>
                                <label for="s_method_<?php echo $_rate->getCode() ?>"><?php echo $this->escapeHtml($_rate->getMethodTitle()) ?>
                                    <?php $_excl = $this->getShippingPrice($_rate->getPrice(), $this->helper('tax')->displayShippingPriceIncludingTax()); ?>
                                    <?php $_incl = $this->getShippingPrice($_rate->getPrice(), true); ?>
                                    <?php echo $_excl; ?>
                                    <?php if ($this->helper('tax')->displayShippingBothPrices() && $_incl != $_excl): ?>
                                        (<?php echo $this->__('Incl. Tax'); ?> <?php echo $_incl; ?>)
                                    <?php endif; ?>
                                </label>
                            <?php endif ?>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                </dd>
            <?php endforeach; ?>
            </dl>
            <div class="validation-advice" style="display: none;"></div>
        <?php endif; ?>
        <script type="text/javascript">
            window.olegnaxOSCShipment = new OnestepcheckoutShipment({
                containerSelector: "#olegnax-osc-shipping-method",
                switchMethodInputsSelector: "input[type='radio'][name='shipping_method']",
                saveShipmentUrl: <?php echo Zend_Json::encode($this->getSaveShipmentUrl());?>
            });
        </script>
    </div>
</div>
<?php endif; ?>