
  <section class="mini-slider section-strt">
            <div class="container">
               <div class="row">
                  <div class="col-lg-12 col-md-12 col-sm-6 col-12">
                     <div class="mini-main">
                        <h2>Our Customer Says</h2>
                     </div>
                  </div>
               </div>
               <section class="slider">
  <div class="demo">
        <div class="item">            
            <div class="clearfix">
                <ul id="image-gallery" class="gallery list-unstyled cS-hidden">
                    <li> 
                        <div class="mini-main-content">
                              <div class="mini-left">
                                 <img src="<?php echo Mage::getBaseUrl('media');?>/custom/default.png">
                                 <h2>John Nova</h2>
                                 <p>(25 june, 2018)</p>
                              </div>
                              <p>
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                              </p>
                           </div>
                         </li>
                    <li> 
                       <div class="mini-main-content">
                              <div class="mini-left">
                                 <img src="<?php echo Mage::getBaseUrl('media');?>/custom/default.png">
                                 <h2>John Nova 1</h2>
                                 <p>(25 june, 2018)</p>
                              </div>
                              <p>
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                              </p>
                           </div>
                         </li>
                    <li> 
                       <div class="mini-main-content">
                              <div class="mini-left">
                                 <img src="<?php echo Mage::getBaseUrl('media');?>/custom/default.png">
                                 <h2>John Nova 2</h2>
                                 <p>(25 june, 2018)</p>
                              </div>
                              <p>
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                                 Lorem Ipsum is simply dummy text of the printing and typesetting industry.
                              </p>
                           </div>
                         </li>
                    
                </ul>
            </div>
        </div>
       

    </div>  
 </section>
               <div class="view-btn">
                  <span><a>View All</a></span>
               </div>
            </div>
         </section>
<section class="apparel">
  <h2>Test</h2>
</section>